server:
  port: 9099
  undertow:
    accesslog:
      dir: '' # 日志存放目录
      enabled: false # 是否启动日志
      pattern: common # 日志格式
      prefix: access_log # 日志文件前缀
      suffix: log # 日志文件后缀
    buffer-size: 1024 # 每块buffer的空间大小,越小的空间被利用越充分
    direct-buffers: true # # 是否分配的直接内存
    max-http-post-size: 0 # POST 请求最大大小 0 表示不限制
    threads:
      io: 4 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      worker: 20 # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
spring:
  application:
    name: demo


